Librarian integration
Nautilus-Cyberneering/chinese-ideographs pull request #138
Opened 2022-02-22 10:12 UTC by yeraydavidrodriguez

This pull request will make the repo use Nautilus Librarian as a CLI application instead of a submodule.

Changes:
- Librarian submodule is removed
- All actions that used the old librarian submodule are removed, as now are executed directly by the CLI
- All test images are removed to make new tests
- Gold Images Processing workflow is modified to use the Librarian as a Python CLI application

2022-02-22 13:30 UTC, josecelano requested changes

2022-02-22 13:30 UTC, josecelano commented on .github/workflows/gold-drawings-processing.yml
> -          echo "CURRENT_REF=HEAD" >> $GITHUB_ENV
@yeraydavidrodriguez I think you need to keep these two lines. The `CURRENT_REF` is always the `HEAD` but the `PREVIOUS_REF` is the first commit in the new branch for the pull request. Below I see you are calling the Librarian with:

```
nautilus-librarian gold-images-processing --previous-ref HEAD~1  --current-ref HEAD
```

I think that way we only compare the latest commit with the previous one in the branch. It only works if the branch has two commits if I'm not wrong. We should always use the first and the latest commits in the branch. The first is the `${{ github.base_ref }}`.

2022-02-25 11:34 UTC, yeraydavidrodriguez commented on .github/workflows/gold-drawings-processing.yml
> -          echo "CURRENT_REF=HEAD" >> $GITHUB_ENV
You are right, @josecelano . I apply the needed corrections.

2022-02-25 15:11 UTC, josecelano approved these changes

2022-02-25 15:11 UTC, merged